//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public int ID { get; set; }
        public string TradeName { get; set; }
        public string TradeLevel { get; set; }
        public string SyllabusName { get; set; }
        public string SyllabusFilePath { get; set; }
        public string TestPlanFilePath { get; set; }
        public System.DateTime ActiveDate { get; set; }
        public string DevelopmentOfficer { get; set; }
        public string Manager { get; set; }
        public string Languages { get; set; }
    }
}
